paths:
  /api/products:
    get:
      summary: Obtener todos los productos
      tags:
        - Products
      responses:
        '200':
          description: Respuesta exitosa
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: string
                  payload:
                    type: array
                    items:
                      $ref: "#/components/schemas/Product"
      security:
        - JWT: []

  /api/products/{id}:
    get:
      summary: Obtener un producto por ID
      parameters:
        - in: path
          name: id
          required: true
          description: ID del producto
          schema:
            type: string
      tags:
        - Products
      responses:
        '200':
          description: Respuesta exitosa
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: string
                  payload:
                    $ref: "#/components/schemas/Product"
      security:
        - JWT: []

    post:
      summary: Crear un nuevo producto
      tags:
        - Products
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/Product"
      security:
        - JWT: []

    put:
      summary: Actualizar un producto existente
      tags:
        - Products
      parameters:
        - in: path
          name: id
          required: true
          description: ID del producto
          schema:
            type: string
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/Product"
      security:
        - JWT: []

    delete:
      summary: Eliminar un producto por ID
      tags:
        - Products
      parameters:
        - in: path
          name: id
          required: true
          description: ID del producto
          schema:
            type: string
      responses:
        '200':
          description: Respuesta exitosa
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: string
      security:
        - JWT: []

components:
  schemas:
    Product:
      type: object
      properties:
        title:
          type: string
          description: Título del producto
        description:
          type: string
          description: Descripción del producto
        price:
          type: number
          description: Precio del producto
        status:
          type: boolean
          description: Estado del producto
        code:
          type: string
          description: Código del producto
        category:
          type: string
          description: Categoría del producto
        thumbnail:
          type: string
          description: URL de la imagen del producto
        quantity:
          type: integer
          description: Cantidad disponible del producto
        owner:
          type: string
          description: ID del propietario del producto
      required:
        - title
        - description
        - price
        - status
        - code
        - category
        - thumbnail
        - quantity
        - owner
