const EError = {
	ROUTINE_ERROR: 1,
	INVALID_TYPES_ERROR: 2,
	DATABASE_ERROR: 3,
	PRODUCT_NOT_FOUND: 4, 
	PRODUCT_CREATION_ERROR: 5, 
	PRODUCT_UPDATE_ERROR: 6, 
	PRODUCT_DELETION_ERROR: 7,
	CART_NOT_FOUND: 8, 
	CART_CREATION_ERROR: 9, 
	ADD_PRODUCT_TO_CART_ERROR: 10, 
	REMOVE_PRODUCT_FROM_CART_ERROR: 11, 
	COMPLETE_CART_ERROR: 12, 
  };
  
  export default EError;
  